name: Pull Request

on:
  pull_request: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  trunk_check:
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout

    steps:
      - uses: actions/checkout@v3
      - uses: trunk-io/trunk-action@v1.1.7
