on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn --prefer-offline
        working-directory: ./release-please-packages
      - run: yarn lint
        working-directory: ./release-please-packages
      - run: yarn format
        working-directory: ./release-please-packages
      - run: yarn ci:package
        working-directory: ./release-please-packages
      - uses: ./release-please-packages/
