name: Test Release-Please-Packages
on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 16.x
      - run: yarn --prefer-offline
        working-directory: ./release-please-packages
      - run: yarn lint
        working-directory: ./release-please-packages
      - run: yarn format
        working-directory: ./release-please-packages
      - run: yarn ci:package
        working-directory: ./release-please-packages
      - id: packages
        uses: ./release-please-packages/
        with:
          config-file: .
      - run: echo "${{ steps.packages.outputs.packages }}"
