name: Test Release-Please-Packages
on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn --prefer-offline
        working-directory: ./release-please-packages
      - run: yarn lint
        working-directory: ./release-please-packages
      - run: yarn format
        working-directory: ./release-please-packages
      - run: yarn ci:package
        working-directory: ./release-please-packages
      - id: packages
        uses: ./release-please-packages/
        with:
          config-file: .
      - run: echo "${{ steps.packages.outputs.packages }}"
