name: Test Release-Please-Packages
on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 16.x
      - run: yarn --prefer-offline
        working-directory: ./release-please-packages
      - run: yarn lint
        working-directory: ./release-please-packages
      - run: yarn format
        working-directory: ./release-please-packages
      - run: yarn ci:package
        working-directory: ./release-please-packages
      - id: packages
        uses: ./release-please-packages/
        with:
          config-file: .
      - run: echo "${{ steps.packages.outputs.packages }}"
