name: Renovate Validate

on:
  pull_request:
    paths:
      - .github/workflows/renovate-validate.yaml
      - .github/renovate.json
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  renovate_validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 18
      - run: npx --package=renovate -- renovate-config-validator .github/renovate.json
