name: Renovate Validate

on:
  pull_request:
    paths:
      - .github/workflows/renovate-validate.yaml
      - .github/renovate.json
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  renovate_validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: 18
      - run: npx --package=renovate -- renovate-config-validator .github/renovate.json
