name: Trunk Annotate

on:
  workflow_run:
    workflows:
      - Pull Request
    types:
      - completed

permissions:
  contents: read

jobs:
  trunk_annotate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: trunk-io/trunk-action@97ecd21fe6c743bf7a606791584b683a7995c70e # v1.1.9
        with:
          post-annotations: true # only for fork PRs
