name: Trunk Cache
on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions:
  contents: read

jobs:
  trunk_cache:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: trunk-io/trunk-action@65228585e2c6128315f0f2d5190e2eae7f5c32c6 # v1.1.10
        with:
          check-mode: populate_cache_only
