name: Trunk Upgrade

on:
  schedule:
    - cron: 0 5 * * 1-5
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trunk_upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: trunk-io/trunk-action/upgrade@97ecd21fe6c743bf7a606791584b683a7995c70e # v1.1.9
