name: Trunk Cache
on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions:
  contents: read

jobs:
  trunk_cache:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: trunk-io/trunk-action@f6c5f1b90503c30e02059667dbc247f2257b63c5 # v1.1.15
        with:
          check-mode: populate_cache_only
