name: Trunk Upgrade

on:
  schedule:
    - cron: 0 5 * * 1-5
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trunk_upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: trunk-io/trunk-action/upgrade@v1.1.7
