name: Trunk Annotate

on:
  workflow_run:
    workflows:
      - Pull Request
    types:
      - completed

permissions:
  contents: read

jobs:
  trunk_annotate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: trunk-io/trunk-action@540e7fe497a45ae76370d26d95cc249059c4ac3a # v1.1.12
        with:
          post-annotations: true # only for fork PRs
