name: Trunk Annotate

on:
  workflow_run:
    workflows:
      - Pull Request
    types:
      - completed

permissions:
  contents: read

jobs:
  trunk_annotate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: trunk-io/trunk-action@97ecd21fe6c743bf7a606791584b683a7995c70e # v1.1.9
        with:
          post-annotations: true # only for fork PRs
