name: Trunk Upgrade

on:
  schedule:
    - cron: 0 5 * * 1-5
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trunk_upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: trunk-io/trunk-action/upgrade@bd686325615e9cf5a4ef98372ba94a472f9b5238 # v1.1.14
