name: Trunk Annotate

on:
  workflow_run:
    workflows: ["Pull Request"]
    types: [completed]

jobs:
  trunk_annotate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: trunk-io/trunk-action@v1.1.7
        with:
          post-annotations: true # only for fork PRs