name: Trunk Cache
on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions:
  contents: read

jobs:
  trunk_cache:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: trunk-io/trunk-action@540e7fe497a45ae76370d26d95cc249059c4ac3a # v1.1.12
        with:
          check-mode: populate_cache_only
