name: Trunk Annotate

on:
  workflow_run:
    workflows:
      - Pull Request
    types:
      - completed

permissions:
  contents: read

jobs:
  trunk_annotate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: trunk-io/trunk-action@883e222ef19201ad402ef73e58101ec8186d7d54 # v1.1.7
        with:
          post-annotations: true # only for fork PRs
